{
 "title": "http-data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "testid",
    "label": "Your Test",
    "query": "SELECT DISTINCT test_id from samples;"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Made",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\",\nSUM(value)\nFROM samples\nWHERE\n  $__timeFilter(ts)\n  AND test_id = $testid\n  AND metric = 'counts.http_reqs'\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqs failed" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\",\nMAX(value)\nFROM samples\nWHERE\n  $__timeFilter(ts)\n  AND test_id = $testid\n  AND metric = 'counts.http_req_failed'\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Request Duration (99th percentile)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", MAX(value) AS max_value \nFROM samples \nWHERE metric IN ('counts.http_reqs', 'timers.http_req_duration.p99') AND $__timeFilter(ts)\nGROUP BY ts \nHAVING COUNT(DISTINCT metric) = 2 \nORDER BY max_value DESC "
    }
   ]
  },
  {
   "title": "# of Requests & VUs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time,\nmetric,\nvalue\nFROM samples\nWHERE\n  $__timeFilter(ts)\n  AND test_id = $testid\n  AND metric IN ('vus', 'counts.http_reqs')\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS time,\n  metric,\n  value\nFROM samples\nWHERE\n  $__timeFilter(ts)\n  AND test_id = $testid\n  AND metric IN ('timers.http_req_duration.p99', 'timers.http_req_duration.count')\nORDER BY ts"
    }
   ]
  }
 ]
}