apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api
  labels:
    app: db-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
        - name: db-api
          image: rachwest/edamame:latest
          ports:
            - containerPort: 4444
          env:
            - name: PORT
              value: "4444"
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-port
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-username
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-db
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: aws-region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: aws-secret-access-key
            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: aws-account-id
          volumeMounts:
            - name: pg-dump
              mountPath: /var/pg_dump
      volumes:
        - name: pg-dump
          emptyDir:
            sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db-api-service
spec:
  selector:
    app: db-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30001
