apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    url: psql-service:5432
    database: edamame
    user: edamame_reader
    secureJsonData:
      password:
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
