apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-edamame-test
spec:
  parallelism: 1             # default value
  script:
    configMap:
      name: '1'              # default value
      file: test.js          # default value
  separate: true
  arguments: '--out distributed-statsd'
  runner:
    image: lukeoguro/xk6-statsd:latest
    env:
      - name: K6_STATSD_ADDR
        value: statsd-service:8125
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: K6_STATSD_GAUGE_NAMESPACE
        value: $(POD_NAME).
      - name: K6_STATSD_NAMESPACE
        value: '1.'          # default value
      - name: K6_STATSD_BUFFER_SIZE
        value: '1432'
      - name: K6_STATSD_PUSH_INTERVAL
        value: '0.5s'
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: alpha.eksctl.io/nodegroup-name
                  operator: In
                  values:
                    - load-generators
