apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-edamame-test
spec:
  parallelism: 4
  script:
    configMap:
      name: '1'
      file: test1.js
  arguments: '--out distributed-statsd'
  runner:
    image: lukeoguro/xk6-statsd:latest
    env:
      - name: K6_STATSD_ADDR
        value: statsd-service:8125
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: K6_STATSD_GAUGE_NAMESPACE
        value: $(POD_NAME).
      - name: K6_STATSD_NAMESPACE
        value: '1.'
