apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  labels:
    app: edamame
secretGenerator:
- name: psql-secret
  envs:
  - properties/psql.env
  type: Opaque
  options:
    disableNameSuffixHash: true