apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  labels:
    app: edamame
secretGenerator:
  - name: postgres-secret
    envs:
      - postgres.env
    type: Opaque
    options:
      disableNameSuffixHash: true
