apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: edamame
  region: us-east-1 # default value

nodeGroups:
  - name: ng-gen
    instanceType: m5.24xlarge # Testing: m5.large; Production: m5.24xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 20
    taints:
      - key: "special"
        value: "sysctl-network-capacity"
        effect: NoSchedule
    kubeletExtraConfig:
      allowedUnsafeSysctls:
        - "net.ipv4.tcp_tw_reuse"
        - "net.ipv4.tcp_timestamps"
