apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: edamame
  region: us-east-1 # default value

managedNodeGroups:
  - name: ng-agg
    labels:
    - node-role.kubernetes.io/agg: ''
    instanceType: m5.large # m5zn.xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 1
    preBootstrapCommands:
      - sysctl -w net.core.rmem_default=536870912 # Set to 512M
      - sysctl -w net.core.rmem_max=536870912 # Set to 512M
    taints:
    - key: "special"
      value: "sysctl-udp-buffer"
      effect: NoSchedule

nodeGroups:
  - name: ng-gen
    labels:
    - node-role.kubernetes.io/gen: ''
    instanceType: m5.large # m5.24xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 20
    taints:
    - key: "special"
      value: "sysctl-network-capacity"
      effect: NoSchedule
    kubeletExtraConfig:
      allowedUnsafeSysctls:
        - "net.ipv4.tcp_tw_reuse"
        - "net.ipv4.tcp_timestamps"
