apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: edamame
  region: us-east-1 # default value

managedNodeGroups:
  - name: statsite
    instanceType: m5zn.xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 1
    preBootstrapCommands:
      - sysctl -w net.core.rmem_default=536870912 # Set to 512M
      - sysctl -w net.core.rmem_max=536870912 # Set to 512M

nodeGroups:
  - name: load-generators
    instanceType: m5.large # m5.24xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 20
    kubeletExtraConfig:
      allowedUnsafeSysctls:
        - "net.ipv4.tcp_tw_reuse"
        - "net.ipv4.tcp_timestamps"
