apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
  labels:
    app: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  serviceName: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql
        image: "postgres:latest"
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: postgres-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-initdb
        configMap:
          name: postgres-initdb-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sh: |
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE TABLE tests (
        id serial PRIMARY KEY,
        name varchar(80) UNIQUE,
        start_time timestamp NOT NULL DEFAULT now(),
        end_time timestamp,
        status varchar(10) NOT NULL DEFAULT 'starting',
        script text
      );
      CREATE TABLE samples (
        id SERIAL PRIMARY KEY,
        ts TIMESTAMP,
        metric VARCHAR(255),
        value REAL,
        test_id INT REFERENCES tests(id) ON DELETE CASCADE
      );
      CREATE USER edamame_reader WITH PASSWORD '$POSTGRES_PASSWORD';
      GRANT SELECT ON ALL TABLES IN SCHEMA public TO edamame_reader;
    EOSQL
---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
spec:
  selector:
    app: psql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None
