apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: edamame
  region: us-east-1 # default value

managedNodeGroups:
  - name: statsite
    instanceType: m5.xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 1
    preBootstrapCommands:
      - sysctl -w net.core.rmem_default=134217728 # Set to 128M; 52428800 not tested; 200M tested (209715200)
      - sysctl -w net.core.rmem_max=134217728 # Set to 128M