apiVersion: v1
kind: Service
metadata:
  name: statsd-service
spec:
  selector:
    app: statsite-server
  ports:
    - protocol: "UDP"
      port: 8125
      targetPort: 8125
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsite-server
spec:
  selector:
    matchLabels:
      app: statsite-server
  replicas: 1
  template:
    metadata:
      labels:
        app: statsite-server
    spec:
      containers:
        - name: statsd
          image: lukeoguro/custom-statsite:2.0
          ports:
            - name: statsd
              containerPort: 8125
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: psql-configmap
                  key: psql-host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: psql-configmap
                  key: psql-port
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: psql-username
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: psql-configmap
                  key: psql-db
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: psql-password
          volumeMounts:
          - name: config
            mountPath: /etc/statsite
      volumes:
        - name: config
          configMap:
            name: statsite-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: alpha.eksctl.io/nodegroup-name
                    operator: In
                    values:
                      - statsite